export const CITY_STATES = {
	"IN": {
		"Delhi": [
			"Delhi",
			"New Delhi"
		],
		"Karnataka": [
			"Adyar",
			"Afzalpur",
			"Arsikere",
			"Athni",
			"Ballari",
			"Belagavi",
			"Bengaluru",
			"Chikkamagaluru",
			"Davanagere",
			"Gokak",
			"Hubli-Dharwad",
			"Karwar",
			"Kolar",
			"Lakshmeshwar",
			"Lingsugur",
			"Maddur",
			"Madhugiri",
			"Madikeri",
			"Magadi",
			"Mahalingapura",
			"Malavalli",
			"Malur",
			"Mandya",
			"Mangaluru",
			"Manvi",
			"Mudabidri",
			"Mudalagi",
			"Muddebihal",
			"Mudhol",
			"Mulbagal",
			"Mundargi",
			"Mysore",
			"Nanjangud",
			"Nargund",
			"Navalgund",
			"Nelamangala",
			"Pavagada",
			"Piriyapatna",
			"Puttur",
			"Raayachuru",
			"Rabkavi Banhatti",
			"Ramanagaram",
			"Ramdurg",
			"Ranebennuru",
			"Ranibennur",
			"Robertson Pet",
			"Ron",
			"Sadalagi",
			"Sagara",
			"Sakaleshapura",
			"Sanduru",
			"Sankeshwara",
			"Saundatti-Yellamma",
			"Savanur",
			"Sedam",
			"Shahabad",
			"Shahpur",
			"Shiggaon",
			"Shikaripur",
			"Shivamogga",
			"Shrirangapattana",
			"Sidlaghatta",
			"Sindagi",
			"Sindhagi",
			"Sindhnur",
			"Sira",
			"Sirsi",
			"Siruguppa",
			"Srinivaspur",
			"Surapura",
			"Talikota",
			"Tarikere",
			"Tekkalakote",
			"Terdal",
			"Tiptur",
			"Tumkur",
			"Udupi",
			"Vijayapura",
			"Wadi",
			"Yadgir"
		],
		"Gujarat": [
			"Adalaj",
			"Ahmedabad",
			"Amreli",
			"Anand",
			"Anjar",
			"Ankleshwar",
			"Bharuch",
			"Bhavnagar",
			"Bhuj",
			"Chhapra",
			"Deesa",
			"Dhoraji",
			"Gandhinagar",
			"Godhra",
			"Jamnagar",
			"Kadi",
			"Kapadvanj",
			"Keshod",
			"Khambhat",
			"Lathi",
			"Limbdi",
			"Lunawada",
			"Mahemdabad",
			"Mahesana",
			"Mahuva",
			"Manavadar",
			"Mandvi",
			"Mangrol",
			"Mansa",
			"Modasa",
			"Morvi",
			"Nadiad",
			"Navsari",
			"Padra",
			"Palanpur",
			"Palitana",
			"Pardi",
			"Patan",
			"Petlad",
			"Porbandar",
			"Radhanpur",
			"Rajkot",
			"Rajpipla",
			"Rajula",
			"Ranavav",
			"Rapar",
			"Salaya",
			"Sanand",
			"Savarkundla",
			"Sidhpur",
			"Sihor",
			"Songadh",
			"Surat",
			"Talaja",
			"Thangadh",
			"Tharad",
			"Umbergaon",
			"Umreth",
			"Una",
			"Unjha",
			"Upleta",
			"Vadnagar",
			"Vadodara",
			"Valsad",
			"Vapi",
			"Vapi",
			"Veraval",
			"Vijapur",
			"Viramgam",
			"Visnagar",
			"Vyara",
			"Wadhwan",
			"Wankaner"
		],
		"Telangana": [
			"Adilabad",
			"Bellampalle",
			"Bhadrachalam",
			"Bhainsa",
			"Bhongir",
			"Bodhan",
			"Farooqnagar",
			"Gadwal",
			"Hyderabad",
			"Jagtial",
			"Jangaon",
			"Kagaznagar",
			"Kamareddy",
			"Karimnagar",
			"Khammam",
			"Koratla",
			"Kothagudem",
			"Kyathampalle",
			"Mahbubnagar",
			"Mancherial",
			"Mandamarri",
			"Manuguru",
			"Medak",
			"Miryalaguda",
			"Nagarkurnool",
			"Narayanpet",
			"Nirmal",
			"Nizamabad",
			"Palwancha",
			"Ramagundam",
			"Sadasivpet",
			"Sangareddy",
			"Siddipet",
			"Sircilla",
			"Suryapet",
			"Tandur",
			"Vikarabad",
			"Wanaparthy",
			"Warangal",
			"Yellandu"
		],
		"Tamil Nadu": [
			"Arakkonam",
			"Aruppukkottai",
			"Chennai",
			"Coimbatore",
			"Erode",
			"Gobichettipalayam",
			"Kancheepuram",
			"Karur",
			"Lalgudi",
			"Madurai",
			"Manachanallur",
			"Nagapattinam",
			"Nagercoil",
			"Namagiripettai",
			"Namakkal",
			"Nandivaram-Guduvancheri",
			"Nanjikottai",
			"Natham",
			"Nellikuppam",
			"Neyveli (TS)",
			"O Valley",
			"Oddanchatram",
			"P.N.Patti",
			"Pacode",
			"Padmanabhapuram",
			"Palani",
			"Palladam",
			"Pallapatti",
			"Pallikonda",
			"Panagudi",
			"Panruti",
			"Paramakudi",
			"Parangipettai",
			"Pattukkottai",
			"Perambalur",
			"Peravurani",
			"Periyakulam",
			"Periyasemur",
			"Pernampattu",
			"Pollachi",
			"Polur",
			"Ponneri",
			"Pudukkottai",
			"Pudupattinam",
			"Puliyankudi",
			"Punjaipugalur",
			"Rajapalayam",
			"Ramanathapuram",
			"Rameshwaram",
			"Ranipet",
			"Rasipuram",
			"Salem",
			"Sankarankovil",
			"Sankari",
			"Sathyamangalam",
			"Sattur",
			"Shenkottai",
			"Sholavandan",
			"Sholingur",
			"Sirkali",
			"Sivaganga",
			"Sivagiri",
			"Sivakasi",
			"Srivilliputhur",
			"Surandai",
			"Suriyampalayam",
			"Tenkasi",
			"Thammampatti",
			"Thanjavur",
			"Tharamangalam",
			"Tharangambadi",
			"Theni Allinagaram",
			"Thirumangalam",
			"Thirupuvanam",
			"Thiruthuraipoondi",
			"Thiruvallur",
			"Thiruvarur",
			"Thuraiyur",
			"Tindivanam",
			"Tiruchendur",
			"Tiruchengode",
			"Tiruchirappalli",
			"Tirukalukundram",
			"Tirukkoyilur",
			"Tirunelveli",
			"Tirupathur",
			"Tirupathur",
			"Tiruppur",
			"Tiruttani",
			"Tiruvannamalai",
			"Tiruvethipuram",
			"Tittakudi",
			"Udhagamandalam",
			"Udumalaipettai",
			"Unnamalaikadai",
			"Usilampatti",
			"Uthamapalayam",
			"Uthiramerur",
			"Vadakkuvalliyur",
			"Vadalur",
			"Vadipatti",
			"Valparai",
			"Vandavasi",
			"Vaniyambadi",
			"Vedaranyam",
			"Vellakoil",
			"Vellore",
			"Vikramasingapuram",
			"Viluppuram",
			"Virudhachalam",
			"Virudhunagar",
			"Viswanatham"
		],
		"West Bengal": [
			"Adra",
			"AlipurdUrban Agglomerationr",
			"Arambagh",
			"Asansol",
			"Baharampur",
			"Balurghat",
			"Bankura",
			"Darjiling",
			"English Bazar",
			"Gangarampur",
			"Habra",
			"Hugli-Chinsurah",
			"Jalpaiguri",
			"Jhargram",
			"Kalimpong",
			"Kharagpur",
			"Kolkata",
			"Mainaguri",
			"Malda",
			"Mathabhanga",
			"Medinipur",
			"Memari",
			"Monoharpur",
			"Murshidabad",
			"Nabadwip",
			"Naihati",
			"Panchla",
			"PandUrban Agglomeration",
			"Paschim Punropara",
			"Purulia",
			"Raghunathganj",
			"Raghunathpur",
			"Raiganj",
			"Rampurhat",
			"Ranaghat",
			"Sainthia",
			"Santipur",
			"Siliguri",
			"Sonamukhi",
			"Srirampore",
			"Suri",
			"Taki",
			"Tamluk",
			"Tarakeswar"
		],
		"Maharashtra": [
			"Achalpur",
			"Ahmednagar",
			"Akola",
			"Akot",
			"Amalner",
			"Ambejogai",
			"Amravati",
			"Anjangaon",
			"Arvi",
			"Aurangabad",
			"Bhiwandi",
			"Dhule",
			"Ichalkaranji",
			"Kalyan-Dombivali",
			"Karjat",
			"Latur",
			"Loha",
			"Lonar",
			"Lonavla",
			"Mahad",
			"Malegaon",
			"Malkapur",
			"Mangalvedhe",
			"Mangrulpir",
			"Manjlegaon",
			"Manmad",
			"Manwath",
			"Mehkar",
			"Mhaswad",
			"Morshi",
			"Mukhed",
			"Mul",
			"Murtijapur",
			"Mumbai",
			"Nagpur",
			"Nanded-Waghala",
			"Nandgaon",
			"Nandura",
			"Nandurbar",
			"Narkhed",
			"Nashik",
			"Nawapur",
			"Nilanga",
			"Osmanabad",
			"Ozar",
			"Pachora",
			"Paithan",
			"Palghar",
			"Pandharkaoda",
			"Pandharpur",
			"Panvel",
			"Parbhani",
			"Parli",
			"Partur",
			"Pathardi",
			"Pathri",
			"Patur",
			"Pauni",
			"Pen",
			"Phaltan",
			"Pulgaon",
			"Pune",
			"Purna",
			"Pusad",
			"Rahuri",
			"Rajura",
			"Ramtek",
			"Ratnagiri",
			"Raver",
			"Risod",
			"Sailu",
			"Sangamner",
			"Sangli",
			"Sangole",
			"Sasvad",
			"Satana",
			"Satara",
			"Savner",
			"Sawantwadi",
			"Shahade",
			"Shegaon",
			"Shendurjana",
			"Shirdi",
			"Shirpur-Warwade",
			"Shirur",
			"Shrigonda",
			"Shrirampur",
			"Sillod",
			"Sinnar",
			"Solapur",
			"Soyagaon",
			"Talegaon Dabhade",
			"Talode",
			"Tasgaon",
			"Tirora",
			"Tuljapur",
			"Tumsar",
			"Uchgaon",
			"Udgir",
			"Umarga",
			"Umarkhed",
			"Umred",
			"Uran",
			"Uran Islampur",
			"Vadgaon Kasba",
			"Vaijapur",
			"Vasai-Virar",
			"Vita",
			"Wadgaon Road",
			"Wai",
			"Wani",
			"Wardha",
			"Warora",
			"Warud",
			"Washim",
			"Yavatmal",
			"Yawal",
			"Yevla"
		],
		"Rajasthan": [
			"Ajmer",
			"Alwar",
			"Barmer",
			"Bharatpur",
			"Bhilwara",
			"Bikaner",
			"Jaipur",
			"Jodhpur",
			"Kota",
			"Lachhmangarh",
			"Ladnu",
			"Lakheri",
			"Lalsot",
			"Losal",
			"Makrana",
			"Malpura",
			"Mandalgarh",
			"Mandawa",
			"Mangrol",
			"Merta City",
			"Mount Abu",
			"Nadbai",
			"Nagar",
			"Nagaur",
			"Nasirabad",
			"Nathdwara",
			"Neem-Ka-Thana",
			"Nimbahera",
			"Nohar",
			"Nokha",
			"Pali",
			"Phalodi",
			"Phulera",
			"Pilani",
			"Pilibanga",
			"Pindwara",
			"Pipar City",
			"Prantij",
			"Pratapgarh",
			"Raisinghnagar",
			"Rajakhera",
			"Rajaldesar",
			"Rajgarh (Alwar)",
			"Rajgarh (Churu)",
			"Rajsamand",
			"Ramganj Mandi",
			"Ramngarh",
			"Ratangarh",
			"Rawatbhata",
			"Rawatsar",
			"Reengus",
			"Sadri",
			"Sadulpur",
			"Sadulshahar",
			"Sagwara",
			"Sambhar",
			"Sanchore",
			"Sangaria",
			"Sardarshahar",
			"Sawai Madhopur",
			"Shahpura",
			"Shahpura",
			"Sheoganj",
			"Sikar",
			"Sirohi",
			"Sojat",
			"Sri Madhopur",
			"Sujangarh",
			"Sumerpur",
			"Suratgarh",
			"Takhatgarh",
			"Taranagar",
			"Todabhim",
			"Todaraisingh",
			"Tonk",
			"Udaipur",
			"Udaipurwati",
			"Vijainagar, Ajmer"
		],
		"Uttar Pradesh": [
			"Achhnera",
			"Agra",
			"Aligarh",
			"Allahabad",
			"Amroha",
			"Azamgarh",
			"Bahraich",
			"Chandausi",
			"Etawah",
			"Fatehpur Sikri",
			"Firozabad",
			"Hapur",
			"Hardoi ",
			"Jhansi",
			"Kalpi",
			"Kanpur",
			"Khair",
			"Laharpur",
			"Lakhimpur",
			"Lal Gopalganj Nindaura",
			"Lalganj",
			"Lalitpur",
			"Lar",
			"Loni",
			"Lucknow",
			"Mathura",
			"Meerut",
			"Mirzapur",
			"Modinagar",
			"Moradabad",
			"Nagina",
			"Najibabad",
			"Nakur",
			"Nanpara",
			"Naraura",
			"Naugawan Sadat",
			"Nautanwa",
			"Nawabganj",
			"Nehtaur",
			"Niwai",
			"Noida",
			"Noorpur",
			"Obra",
			"Orai",
			"Padrauna",
			"Palia Kalan",
			"Parasi",
			"Phulpur",
			"Pihani",
			"Pilibhit",
			"Pilkhuwa",
			"Powayan",
			"Pukhrayan",
			"Puranpur",
			"PurqUrban Agglomerationzi",
			"Purwa",
			"Rae Bareli",
			"Rampur",
			"Rampur Maniharan",
			"Rasra",
			"Rath",
			"Renukoot",
			"Reoti",
			"Robertsganj",
			"Rudauli",
			"Rudrapur",
			"SUrban Agglomerationr",
			"Sadabad",
			"Safipur",
			"Saharanpur",
			"Sahaspur",
			"Sahaswan",
			"Sahawar",
			"Sahjanwa",
			"Saidpur",
			"Sambhal",
			"Samdhan",
			"Samthar",
			"Sandi",
			"Sandila",
			"Sardhana",
			"Seohara",
			"Shahabad, Hardoi",
			"Shahabad, Rampur",
			"Shahganj",
			"Shahjahanpur",
			"Shamli",
			"Shamsabad, Agra",
			"Shamsabad, Farrukhabad",
			"Sherkot",
			"Shikarpur, Bulandshahr",
			"Shikohabad",
			"Shishgarh",
			"Siana",
			"Sikanderpur",
			"Sikandra Rao",
			"Sikandrabad",
			"Sirsaganj",
			"Sirsi",
			"Sitapur",
			"Soron",
			"Sultanpur",
			"Sumerpur",
			"Tanda",
			"Thakurdwara",
			"Thana Bhawan",
			"Tilhar",
			"Tirwaganj",
			"Tulsipur",
			"Tundla",
			"Ujhani",
			"Unnao",
			"Utraula",
			"Varanasi",
			"Vrindavan",
			"Warhapur",
			"Zaidpur",
			"Zamania"
		],
		"Bihar": [
			"Araria",
			"Arrah",
			"Arwal",
			"Asarganj",
			"Aurangabad",
			"Bagaha",
			"Barh",
			"Begusarai",
			"Bettiah",
			"BhabUrban Agglomeration",
			"Bhagalpur",
			"Buxar",
			"Chhapra",
			"Darbhanga",
			"Dehri-on-Sone",
			"Dumraon",
			"Forbesganj",
			"Gaya",
			"Gopalganj",
			"Hajipur",
			"Jamalpur",
			"Jamui",
			"Jehanabad",
			"Katihar",
			"Kishanganj",
			"Lakhisarai",
			"Lalganj",
			"Madhepura",
			"Madhubani",
			"Maharajganj",
			"Mahnar Bazar",
			"Makhdumpur",
			"Maner",
			"Manihari",
			"Marhaura",
			"Masaurhi",
			"Mirganj",
			"Mokameh",
			"Motihari",
			"Motipur",
			"Munger",
			"Murliganj",
			"Muzaffarpur",
			"Narkatiaganj",
			"Naugachhia",
			"Nawada",
			"Nokha",
			"Patna",
			"Piro",
			"Purnia",
			"Rafiganj",
			"Rajgir",
			"Ramnagar",
			"Raxaul Bazar",
			"Revelganj",
			"Rosera",
			"Saharsa",
			"Samastipur",
			"Sasaram",
			"Sheikhpura",
			"Sheohar",
			"Sherghati",
			"Silao",
			"Sitamarhi",
			"Siwan",
			"Sonepur",
			"Sugauli",
			"Sultanganj",
			"Supaul",
			"Warisaliganj"
		],
		"Madhya Pradesh": [
			"Alirajpur",
			"Ashok Nagar",
			"Balaghat",
			"Bhopal",
			"Ganjbasoda",
			"Gwalior",
			"Indore",
			"Itarsi",
			"Jabalpur",
			"Lahar",
			"Maharajpur",
			"Mahidpur",
			"Maihar",
			"Malaj Khand",
			"Manasa",
			"Manawar",
			"Mandideep",
			"Mandla",
			"Mandsaur",
			"Mauganj",
			"Mhow Cantonment",
			"Mhowgaon",
			"Morena",
			"Multai",
			"Mundi",
			"Murwara (Katni)",
			"Nagda",
			"Nainpur",
			"Narsinghgarh",
			"Narsinghgarh",
			"Neemuch",
			"Nepanagar",
			"Niwari",
			"Nowgong",
			"Nowrozabad (Khodargama)",
			"Pachore",
			"Pali",
			"Panagar",
			"Pandhurna",
			"Panna",
			"Pasan",
			"Pipariya",
			"Pithampur",
			"Porsa",
			"Prithvipur",
			"Raghogarh-Vijaypur",
			"Rahatgarh",
			"Raisen",
			"Rajgarh",
			"Ratlam",
			"Rau",
			"Rehli",
			"Rewa",
			"Sabalgarh",
			"Sagar",
			"Sanawad",
			"Sarangpur",
			"Sarni",
			"Satna",
			"Sausar",
			"Sehore",
			"Sendhwa",
			"Seoni",
			"Seoni-Malwa",
			"Shahdol",
			"Shajapur",
			"Shamgarh",
			"Sheopur",
			"Shivpuri",
			"Shujalpur",
			"Sidhi",
			"Sihora",
			"Singrauli",
			"Sironj",
			"Sohagpur",
			"Tarana",
			"Tikamgarh",
			"Ujjain",
			"Umaria",
			"Vidisha",
			"Vijaypur",
			"Wara Seoni"
		],
		"Andhra Pradesh": [
			"Adoni",
			"Amalapuram",
			"Anakapalle",
			"Anantapur",
			"Bapatla",
			"Bheemunipatnam",
			"Bhimavaram",
			"Bobbili",
			"Chilakaluripet",
			"Chirala",
			"Chittoor",
			"Dharmavaram",
			"Eluru",
			"Gooty",
			"Gudivada",
			"Gudur",
			"Guntakal",
			"Guntur",
			"Hindupur",
			"Jaggaiahpet",
			"Jammalamadugu",
			"Kadapa",
			"Kadiri",
			"Kakinada",
			"Kandukur",
			"Kavali",
			"Kovvur",
			"Kurnool",
			"Macherla",
			"Machilipatnam",
			"Madanapalle",
			"Mandapeta",
			"Markapur",
			"Nagari",
			"Naidupet",
			"Nandyal",
			"Narasapuram",
			"Narasaraopet",
			"Narsipatnam",
			"Nellore",
			"Nidadavole",
			"Nuzvid",
			"Ongole",
			"Palacole",
			"Palasa Kasibugga",
			"Parvathipuram",
			"Pedana",
			"Peddapuram",
			"Pithapuram",
			"Ponnur",
			"Proddatur",
			"Punganur",
			"Puttur",
			"Rajahmundry",
			"Rajam",
			"Rajampet",
			"Ramachandrapuram",
			"Rayachoti",
			"Rayadurg",
			"Renigunta",
			"Repalle",
			"Salur",
			"Samalkot",
			"Sattenapalle",
			"Srikakulam",
			"Srikalahasti",
			"Srisailam Project (Right Flank Colony) Township",
			"Sullurpeta",
			"Tadepalligudem",
			"Tadpatri",
			"Tanuku",
			"Tenali",
			"Tirupati",
			"Tiruvuru",
			"Tuni",
			"Uravakonda",
			"Venkatagiri",
			"Vijayawada",
			"Vinukonda",
			"Visakhapatnam",
			"Vizianagaram",
			"Yemmiganur",
			"Yerraguntla"
		],
		"Punjab": [
			"Amritsar",
			"Barnala",
			"Batala",
			"Bathinda",
			"Dhuri",
			"Faridkot",
			"Fazilka",
			"Firozpur",
			"Firozpur Cantt.",
			"Gobindgarh",
			"Gurdaspur",
			"Hoshiarpur",
			"Jagraon",
			"Jalandhar",
			"Jalandhar Cantt.",
			"Kapurthala",
			"Khanna",
			"Kharar",
			"Kot Kapura",
			"Longowal",
			"Ludhiana",
			"Malerkotla",
			"Malout",
			"Mansa",
			"Moga",
			"Mohali",
			"Morinda, India",
			"Mukerian",
			"Muktsar",
			"Nabha",
			"Nakodar",
			"Nangal",
			"Nawanshahr",
			"Pathankot",
			"Patiala",
			"Patti",
			"Pattran",
			"Phagwara",
			"Phillaur",
			"Qadian",
			"Raikot",
			"Rajpura",
			"Rampura Phul",
			"Rupnagar",
			"Samana",
			"Sangrur",
			"Sirhind Fatehgarh Sahib",
			"Sujanpur",
			"Sunam",
			"Talwara",
			"Tarn Taran",
			"Urmar Tanda",
			"Zira",
			"Zirakpur"
		],
		"Haryana": [
			"Bahadurgarh",
			"Bhiwani",
			"Charkhi Dadri",
			"Faridabad",
			"Fatehabad",
			"Gohana",
			"Gurgaon",
			"Hansi",
			"Hisar",
			"Jind",
			"Kaithal",
			"Karnal",
			"Ladwa",
			"Mahendragarh",
			"Mandi Dabwali",
			"Narnaul",
			"Narwana",
			"Palwal",
			"Panchkula",
			"Panipat",
			"Pehowa",
			"Pinjore",
			"Rania",
			"Ratia",
			"Rewari",
			"Rohtak",
			"Safidon",
			"Samalkha",
			"Sarsod",
			"Shahbad",
			"Sirsa",
			"Sohna",
			"Sonipat",
			"Taraori",
			"Thanesar",
			"Tohana",
			"Yamunanagar"
		],
		"Jammu and Kashmir": [
			"Anantnag",
			"Baramula",
			"Jammu",
			"KathUrban Agglomeration",
			"Punch",
			"Rajauri",
			"Sopore",
			"Srinagar",
			"Udhampur"
		],
		"Jharkhand": [
			"Adityapur",
			"Bokaro Steel City",
			"Chaibasa",
			"Chatra",
			"Chirkunda",
			"Deoghar",
			"Dhanbad",
			"Dumka",
			"Giridih",
			"Gumia",
			"Hazaribag",
			"Jamshedpur",
			"Jhumri Tilaiya",
			"Lohardaga",
			"Madhupur",
			"Medininagar (Daltonganj)",
			"Mihijam",
			"Musabani",
			"Pakaur",
			"Patratu",
			"Phusro",
			"Ramgarh",
			"Ranchi",
			"Sahibganj",
			"Saunda",
			"Simdega",
			"Tenu dam-cum-Kathhara"
		],
		"Chhattisgarh": [
			"Ambikapur",
			"Bhatapara",
			"Bhilai Nagar",
			"Bilaspur",
			"Chirmiri",
			"Dalli-Rajhara",
			"Dhamtari",
			"Durg",
			"Jagdalpur",
			"Korba",
			"Mahasamund",
			"Manendragarh",
			"Mungeli",
			"Naila Janjgir",
			"Raigarh",
			"Raipur",
			"Rajnandgaon",
			"Sakti",
			"Tilda Newra"
		],
		"Assam": [
			"Barpeta",
			"Bongaigaon City",
			"Dhubri",
			"Dibrugarh",
			"Diphu",
			"Dispur",
			"Goalpara",
			"Guwahati",
			"Jorhat",
			"Karimganj",
			"Lanka",
			"Lumding",
			"Mangaldoi",
			"Mankachar",
			"Margherita",
			"Mariani",
			"Marigaon",
			"Nagaon",
			"Nalbari",
			"North Lakhimpur",
			"Rangia",
			"Sibsagar",
			"Silapathar",
			"Silchar",
			"Tezpur",
			"Tinsukia"
		],
		"Chandigarh": [
			"Chandigarh"
		],
		"Odisha": [
			"Balangir",
			"Baleshwar Town",
			"Barbil",
			"Bargarh",
			"Baripada Town",
			"Bhadrak",
			"Bhawanipatna",
			"Bhubaneswar",
			"Brahmapur",
			"Byasanagar",
			"Cuttack",
			"Dhenkanal",
			"Jatani",
			"Jharsuguda",
			"Kendrapara",
			"Kendujhar",
			"Malkangiri",
			"Nabarangapur",
			"Paradip",
			"Parlakhemundi",
			"Pattamundai",
			"Phulabani",
			"Puri",
			"Rairangpur",
			"Rajagangapur",
			"Raurkela",
			"Rayagada",
			"Sambalpur",
			"Soro",
			"Sunabeda",
			"Sundargarh",
			"Talcher",
			"Tarbha",
			"Titlagarh"
		],
		"Kerala": [
			"Adoor",
			"Alappuzha",
			"Attingal",
			"Chalakudy",
			"Changanassery",
			"Cherthala",
			"Chittur-Thathamangalam",
			"Guruvayoor",
			"Kanhangad",
			"Kannur",
			"Kasaragod",
			"Kayamkulam",
			"Kochi",
			"Kodungallur",
			"Kollam",
			"Kottayam",
			"Koyilandy",
			"Kozhikode",
			"Kunnamkulam",
			"Malappuram",
			"Mattannur",
			"Mavelikkara",
			"Mavoor",
			"Muvattupuzha",
			"Nedumangad",
			"Neyyattinkara",
			"Nilambur",
			"Ottappalam",
			"Palai",
			"Palakkad",
			"Panamattom",
			"Panniyannur",
			"Pappinisseri",
			"Paravoor",
			"Pathanamthitta",
			"Peringathur",
			"Perinthalmanna",
			"Perumbavoor",
			"Ponnani",
			"Punalur",
			"Puthuppally",
			"Shoranur",
			"Taliparamba",
			"Thiruvalla",
			"Thiruvananthapuram",
			"Thodupuzha",
			"Thrissur",
			"Tirur",
			"Vaikom",
			"Varkala",
			"Vatakara"
		],
		"Uttarakhand": [
			"Bageshwar",
			"Dehradun",
			"Haldwani-cum-Kathgodam",
			"Hardwar",
			"Kashipur",
			"Manglaur",
			"Mussoorie",
			"Nagla",
			"Nainital",
			"Pauri",
			"Pithoragarh",
			"Ramnagar",
			"Rishikesh",
			"Roorkee",
			"Rudrapur",
			"Sitarganj",
			"Srinagar",
			"Tehri"
		],
		"Puducherry": [
			"Karaikal",
			"Mahe",
			"Pondicherry",
			"Yanam"
		],
		"Tripura": [
			"Agartala",
			"Belonia",
			"Dharmanagar",
			"Kailasahar",
			"Khowai",
			"Pratapgarh",
			"Udaipur"
		],
		"Mizoram": [
			"Aizawl",
			"Lunglei",
			"Saiha"
		],
		"Meghalaya": [
			"Nongstoin",
			"Shillong",
			"Tura"
		],
		"Manipur": [
			"Imphal",
			"Lilong",
			"Mayang Imphal",
			"Thoubal"
		],
		"Himachal Pradesh": [
			"Kullu",
			"Mandi",
			"Nahan",
			"Palampur",
			"Shimla",
			"Solan",
			"Sundarnagar"
		],
		"Nagaland": [
			"Dimapur",
			"Kohima",
			"Mokokchung",
			"Tuensang",
			"Wokha",
			"Zunheboto"
		],
		"Goa": [
			"Mapusa",
			"Margao",
			"Marmagao",
			"Panaji"
		],
		"Andaman and Nicobar Islands": [
			"Port Blair"
		],
		"Arunachal Pradesh": [
			"Naharlagun",
			"Pasighat"
		],
		"Dadra and Nagar Haveli": [
			"Silvassa"
		],
		"Himachal Praddesh": [
			"Manali"
		]
	},
	"US": {
		"Alabama": [
			"Andalusia",
			"Anniston",
			"Athens",
			"Atmore",
			"Auburn",
			"Bessemer",
			"Birmingham",
			"Chickasaw",
			"Clanton",
			"Cullman",
			"Decatur",
			"Demopolis",
			"Dothan",
			"Enterprise",
			"Eufaula",
			"Florence",
			"Fort Payne",
			"Gadsden",
			"Greenville",
			"Guntersville",
			"Huntsville",
			"Jasper",
			"Marion",
			"Mobile",
			"Montgomery",
			"Opelika",
			"Ozark",
			"Phenix City",
			"Prichard",
			"Scottsboro",
			"Selma",
			"Sheffield",
			"Sylacauga",
			"Talladega",
			"Troy",
			"Tuscaloosa",
			"Tuscumbia",
			"Tuskegee"
		],
		"Alaska": [
			"Anchorage",
			"Cordova",
			"Fairbanks",
			"Haines",
			"Homer",
			"Juneau",
			"Ketchikan",
			"Kodiak",
			"Kotzebue",
			"Nome",
			"Palmer",
			"Seward",
			"Sitka",
			"Skagway",
			"Valdez"
		],
		"Arizona": [
			"Ajo",
			"Avondale",
			"Bisbee",
			"Casa Grande",
			"Chandler",
			"Clifton",
			"Douglas",
			"Flagstaff",
			"Florence",
			"Gila Bend",
			"Glendale",
			"Globe",
			"Kingman",
			"Lake Havasu City",
			"Mesa",
			"Nogales",
			"Oraibi",
			"Phoenix",
			"Prescott",
			"Scottsdale",
			"Sierra Vista",
			"Tempe",
			"Tombstone",
			"Tucson",
			"Walpi",
			"Window Rock",
			"Winslow",
			"Yuma"
		],
		"Arkansas": [
			"Arkadelphia",
			"Arkansas Post",
			"Batesville",
			"Benton",
			"Blytheville",
			"Camden",
			"Conway",
			"Crossett",
			"El Dorado",
			"Fayetteville",
			"Forrest City",
			"Fort Smith",
			"Harrison",
			"Helena",
			"Hope",
			"Hot Springs",
			"Jacksonville",
			"Jonesboro",
			"Little Rock",
			"Magnolia",
			"Morrilton",
			"Newport",
			"North Little Rock",
			"Osceola",
			"Pine Bluff",
			"Rogers",
			"Searcy",
			"Stuttgart",
			"Van Buren",
			"West Memphis"
		],
		"California": [
			"Alameda",
			"Alhambra",
			"Anaheim",
			"Antioch",
			"Arcadia",
			"Bakersfield",
			"Barstow",
			"Belmont",
			"Berkeley",
			"Beverly Hills",
			"Brea",
			"Buena Park",
			"Burbank",
			"Calexico",
			"Calistoga",
			"Carlsbad",
			"Carmel",
			"Chico",
			"Chula Vista",
			"Claremont",
			"Compton",
			"Concord",
			"Corona",
			"Coronado",
			"Costa Mesa",
			"Culver City",
			"Daly City",
			"Davis",
			"Downey",
			"El Centro",
			"El Cerrito",
			"El Monte",
			"Escondido",
			"Eureka",
			"Fairfield",
			"Fontana",
			"Fremont",
			"Fresno",
			"Fullerton",
			"Garden Grove",
			"Glendale",
			"Hayward",
			"Hollywood",
			"Huntington Beach",
			"Indio",
			"Inglewood",
			"Irvine",
			"La Habra",
			"Laguna Beach",
			"Lancaster",
			"Livermore",
			"Lodi",
			"Lompoc",
			"Long Beach",
			"Los Angeles",
			"Malibu",
			"Martinez",
			"Marysville",
			"Menlo Park",
			"Merced",
			"Modesto",
			"Monterey",
			"Mountain View",
			"Napa",
			"Needles",
			"Newport Beach",
			"Norwalk",
			"Novato",
			"Oakland",
			"Oceanside",
			"Ojai",
			"Ontario",
			"Orange",
			"Oroville",
			"Oxnard",
			"Pacific Grove",
			"Palm Springs",
			"Palmdale",
			"Palo Alto",
			"Pasadena",
			"Petaluma",
			"Pomona",
			"Port Hueneme",
			"Rancho Cucamonga",
			"Red Bluff",
			"Redding",
			"Redlands",
			"Redondo Beach",
			"Redwood City",
			"Richmond",
			"Riverside",
			"Roseville",
			"Sacramento",
			"Salinas",
			"San Bernardino",
			"San Clemente",
			"San Diego",
			"San Fernando",
			"San Francisco",
			"San Gabriel",
			"San Jose",
			"San Juan Capistrano",
			"San Leandro",
			"San Luis Obispo",
			"San Marino",
			"San Mateo",
			"San Pedro",
			"San Rafael",
			"San Simeon",
			"Santa Ana",
			"Santa Barbara",
			"Santa Clara",
			"Santa Clarita",
			"Santa Cruz",
			"Santa Monica",
			"Santa Rosa",
			"Sausalito",
			"Simi Valley",
			"Sonoma",
			"South San Francisco",
			"Stockton",
			"Sunnyvale",
			"Susanville",
			"Thousand Oaks",
			"Torrance",
			"Turlock",
			"Ukiah",
			"Vallejo",
			"Ventura",
			"Victorville",
			"Visalia",
			"Walnut Creek",
			"Watts",
			"West Covina",
			"Whittier",
			"Woodland",
			"Yorba Linda",
			"Yuba City"
		],
		"Colorado": [
			"Alamosa",
			"Aspen",
			"Aurora",
			"Boulder",
			"Breckenridge",
			"Brighton",
			"Canon City",
			"Central City",
			"Climax",
			"Colorado Springs",
			"Cortez",
			"Cripple Creek",
			"Denver",
			"Durango",
			"Englewood",
			"Estes Park",
			"Fort Collins",
			"Fort Morgan",
			"Georgetown",
			"Glenwood Springs",
			"Golden",
			"Grand Junction",
			"Greeley",
			"Gunnison",
			"La Junta",
			"Leadville",
			"Littleton",
			"Longmont",
			"Loveland",
			"Montrose",
			"Ouray",
			"Pagosa Springs",
			"Pueblo",
			"Silverton",
			"Steamboat Springs",
			"Sterling",
			"Telluride",
			"Trinidad",
			"Vail",
			"Walsenburg",
			"Westminster"
		],
		"Connecticut": [
			"Ansonia",
			"Berlin",
			"Bloomfield",
			"Branford",
			"Bridgeport",
			"Bristol",
			"Coventry",
			"Danbury",
			"Darien",
			"Derby",
			"East Hartford",
			"East Haven",
			"Enfield",
			"Fairfield",
			"Farmington",
			"Greenwich",
			"Groton",
			"Guilford",
			"Hamden",
			"Hartford",
			"Lebanon",
			"Litchfield",
			"Manchester",
			"Mansfield",
			"Meriden",
			"Middletown",
			"Milford",
			"Mystic",
			"Naugatuck",
			"New Britain",
			"New Haven",
			"New London",
			"North Haven",
			"Norwalk",
			"Norwich",
			"Old Saybrook",
			"Orange",
			"Seymour",
			"Shelton",
			"Simsbury",
			"Southington",
			"Stamford",
			"Stonington",
			"Stratford",
			"Torrington",
			"Wallingford",
			"Waterbury",
			"Waterford",
			"Watertown",
			"West Hartford",
			"West Haven",
			"Westport",
			"Wethersfield",
			"Willimantic",
			"Windham",
			"Windsor",
			"Windsor Locks",
			"Winsted"
		],
		"Delaware": [
			"Apalachicola",
			"Bartow",
			"Belle Glade",
			"Boca Raton",
			"Bradenton",
			"Cape Coral",
			"Clearwater",
			"Cocoa Beach",
			"Cocoa - Rockledge",
			"Coral Gables",
			"Daytona Beach",
			"De Land",
			"Deerfield Beach",
			"Delray Beach",
			"Dover",
			"Fernandina Beach",
			"Florida",
			"Fort Lauderdale",
			"Fort Myers",
			"Fort Pierce",
			"Fort Walton Beach",
			"Gainesville",
			"Hallandale Beach",
			"Hialeah",
			"Hollywood",
			"Homestead",
			"Jacksonville",
			"Key West",
			"Lake City",
			"Lake Wales",
			"Lakeland",
			"Largo",
			"Lewes",
			"Melbourne",
			"Miami",
			"Miami Beach",
			"Milford",
			"Naples",
			"New Castle",
			"New Smyrna Beach",
			"Newark",
			"Ocala",
			"Orlando",
			"Ormond Beach",
			"Palatka",
			"Palm Bay",
			"Palm Beach",
			"Panama City",
			"Pensacola",
			"Pompano Beach",
			"Saint Augustine",
			"Saint Petersburg",
			"Sanford",
			"Sarasota",
			"Sebring",
			"Smyrna",
			"Tallahassee",
			"Tampa",
			"Tarpon Springs",
			"Titusville",
			"Venice",
			"West Palm Beach",
			"White Springs",
			"Wilmington",
			"Winter Haven",
			"Winter Park"
		],
		"Georgia": [
			"Albany",
			"Americus",
			"Andersonville",
			"Athens",
			"Atlanta",
			"Augusta",
			"Bainbridge",
			"Blairsville",
			"Brunswick",
			"Calhoun",
			"Carrollton",
			"Columbus",
			"Dahlonega",
			"Dalton",
			"Darien",
			"Decatur",
			"Douglas",
			"East Point",
			"Fitzgerald",
			"Fort Valley",
			"Gainesville",
			"Hanalei",
			"Hawaii",
			"Hilo",
			"Honaunau",
			"Honolulu",
			"Kahului",
			"Kaneohe",
			"Kapaa",
			"Kawaihae",
			"La Grange",
			"Lahaina",
			"Laie",
			"Macon",
			"Marietta",
			"Milledgeville",
			"Plains",
			"Rome",
			"Savannah",
			"Toccoa",
			"Valdosta",
			"Wahiawa",
			"Wailuku",
			"Waimea",
			"Warm Springs",
			"Warner Robins",
			"Washington",
			"Waycross"
		],
		"Idaho": [
			"Blackfoot",
			"Boise",
			"Bonners Ferry",
			"Caldwell",
			"Coeur d’Alene",
			"Idaho City",
			"Idaho Falls",
			"Kellogg",
			"Lewiston",
			"Moscow",
			"Nampa",
			"Pocatello",
			"Priest River",
			"Rexburg",
			"Sun Valley",
			"Twin Falls"
		],
		"Illinois": [
			"Alton",
			"Arlington Heights",
			"Arthur",
			"Aurora",
			"Belleville",
			"Belvidere",
			"Bloomington",
			"Brookfield",
			"Cahokia",
			"Cairo",
			"Calumet City",
			"Canton",
			"Carbondale",
			"Carlinville",
			"Carthage",
			"Centralia",
			"Champaign",
			"Charleston",
			"Chester",
			"Chicago",
			"Chicago Heights",
			"Cicero",
			"Collinsville",
			"Danville",
			"DeKalb",
			"Decatur",
			"Des Plaines",
			"Dixon",
			"East Moline",
			"East Saint Louis",
			"Effingham",
			"Elgin",
			"Elmhurst",
			"Evanston",
			"Freeport",
			"Galena",
			"Galesburg",
			"Glen Ellyn",
			"Glenview",
			"Granite City",
			"Harrisburg",
			"Herrin",
			"Highland Park",
			"Jacksonville",
			"Joliet",
			"Kankakee",
			"Kaskaskia",
			"Kewanee",
			"La Salle",
			"Lake Forest",
			"Libertyville",
			"Lincoln",
			"Lisle",
			"Lombard",
			"Macomb",
			"Mattoon",
			"Moline",
			"Monmouth",
			"Mount Vernon",
			"Mundelein",
			"Naperville",
			"Nauvoo",
			"Normal",
			"North Chicago",
			"Oak Park",
			"Oregon",
			"Ottawa",
			"Palatine",
			"Park Forest",
			"Park Ridge",
			"Pekin",
			"Peoria",
			"Petersburg",
			"Pontiac",
			"Quincy",
			"Rantoul",
			"River Forest",
			"Rock Island",
			"Rockford",
			"Salem",
			"Shawneetown",
			"Skokie",
			"South Holland",
			"Springfield",
			"Streator",
			"Summit",
			"Urbana",
			"Vandalia",
			"Virden",
			"Waukegan",
			"Wheaton",
			"Wilmette",
			"Winnetka",
			"Wood River",
			"Zion"
		],
		"Indiana": [
			"Anderson",
			"Bedford",
			"Bloomington",
			"Columbus",
			"Connersville",
			"Corydon",
			"Crawfordsville",
			"East Chicago",
			"Elkhart",
			"Elwood",
			"Evansville",
			"Fort Wayne",
			"French Lick",
			"Gary",
			"Geneva",
			"Goshen",
			"Greenfield",
			"Hammond",
			"Hobart",
			"Huntington",
			"Indianapolis",
			"Jeffersonville",
			"Kokomo",
			"Lafayette",
			"Madison",
			"Marion",
			"Michigan City",
			"Mishawaka",
			"Muncie",
			"Nappanee",
			"Nashville",
			"New Albany",
			"New Castle",
			"New Harmony",
			"Peru",
			"Plymouth",
			"Richmond",
			"Santa Claus",
			"Shelbyville",
			"South Bend",
			"Terre Haute",
			"Valparaiso",
			"Vincennes",
			"Wabash",
			"West Lafayette"
		],
		"Iowa": [
			"Amana Colonies",
			"Ames",
			"Boone",
			"Burlington",
			"Cedar Falls",
			"Cedar Rapids",
			"Charles City",
			"Cherokee",
			"Clinton",
			"Council Bluffs",
			"Davenport",
			"Des Moines",
			"Dubuque",
			"Estherville",
			"Fairfield",
			"Fort Dodge",
			"Grinnell",
			"Indianola",
			"Iowa City",
			"Keokuk",
			"Mason City",
			"Mount Pleasant",
			"Muscatine",
			"Newton",
			"Oskaloosa",
			"Ottumwa",
			"Sioux City",
			"Waterloo",
			"Webster City",
			"West Des Moines"
		],
		"Kansas": [
			"Abilene",
			"Arkansas City",
			"Atchison",
			"Chanute",
			"Coffeyville",
			"Council Grove",
			"Dodge City",
			"Emporia",
			"Fort Scott",
			"Garden City",
			"Great Bend",
			"Hays",
			"Hutchinson",
			"Independence",
			"Junction City",
			"Kansas City",
			"Lawrence",
			"Leavenworth",
			"Liberal",
			"Manhattan",
			"McPherson",
			"Medicine Lodge",
			"Newton",
			"Olathe",
			"Osawatomie",
			"Ottawa",
			"Overland Park",
			"Pittsburg",
			"Salina",
			"Shawnee",
			"Smith Center",
			"Topeka",
			"Wichita"
		],
		"Kentucky": [
			"Ashland",
			"Barbourville",
			"Bardstown",
			"Berea",
			"Boonesborough",
			"Bowling Green",
			"Campbellsville",
			"Covington",
			"Danville",
			"Elizabethtown",
			"Frankfort",
			"Harlan",
			"Harrodsburg",
			"Hazard",
			"Henderson",
			"Hodgenville",
			"Hopkinsville",
			"Lexington",
			"Louisville",
			"Mayfield",
			"Maysville",
			"Middlesboro",
			"Newport",
			"Owensboro",
			"Paducah",
			"Paris",
			"Richmond"
		],
		"Louisiana": [
			"Abbeville",
			"Alexandria",
			"Bastrop",
			"Baton Rouge",
			"Bogalusa",
			"Bossier City",
			"Gretna",
			"Houma",
			"Lafayette",
			"Lake Charles",
			"Monroe",
			"Morgan City",
			"Natchitoches",
			"New Iberia",
			"New Orleans",
			"Opelousas",
			"Ruston",
			"Saint Martinville",
			"Shreveport",
			"Thibodaux"
		],
		"Maine": [
			"Auburn",
			"Augusta",
			"Bangor",
			"Bar Harbor",
			"Bath",
			"Belfast",
			"Biddeford",
			"Boothbay Harbor",
			"Brunswick",
			"Calais",
			"Caribou",
			"Castine",
			"Eastport",
			"Ellsworth",
			"Farmington",
			"Fort Kent",
			"Gardiner",
			"Houlton",
			"Kennebunkport",
			"Kittery",
			"Lewiston",
			"Lubec",
			"Machias",
			"Orono",
			"Portland",
			"Presque Isle",
			"Rockland",
			"Rumford",
			"Saco",
			"Scarborough",
			"Waterville",
			"York"
		],
		"Maryland": [
			"Aberdeen",
			"Annapolis",
			"Baltimore",
			"Bethesda - Chevy Chase",
			"Bowie",
			"Cambridge",
			"Catonsville",
			"College Park",
			"Columbia",
			"Cumberland",
			"Easton",
			"Elkton",
			"Emmitsburg",
			"Frederick",
			"Greenbelt",
			"Hagerstown",
			"Hyattsville",
			"Laurel",
			"Oakland",
			"Ocean City",
			"Rockville",
			"Saint Marys City",
			"Salisbury",
			"Silver Spring",
			"Takoma Park",
			"Towson",
			"Westminster"
		],
		"Massachusetts": [
			"Abington",
			"Adams",
			"Amesbury",
			"Amherst",
			"Andover",
			"Arlington",
			"Athol",
			"Attleboro",
			"Barnstable",
			"Bedford",
			"Beverly",
			"Boston",
			"Bourne",
			"Braintree",
			"Brockton",
			"Brookline",
			"Cambridge",
			"Canton",
			"Charlestown",
			"Chelmsford",
			"Chelsea",
			"Chicopee",
			"Clinton",
			"Cohasset",
			"Concord",
			"Danvers",
			"Dartmouth",
			"Dedham",
			"Dennis",
			"Duxbury",
			"Eastham",
			"Edgartown",
			"Everett",
			"Fairhaven",
			"Fall River",
			"Falmouth",
			"Fitchburg",
			"Framingham",
			"Gloucester",
			"Great Barrington",
			"Greenfield",
			"Groton",
			"Harwich",
			"Haverhill",
			"Hingham",
			"Holyoke",
			"Hyannis",
			"Ipswich",
			"Lawrence",
			"Lenox",
			"Leominster",
			"Lexington",
			"Lowell",
			"Ludlow",
			"Lynn",
			"Malden",
			"Marblehead",
			"Marlborough",
			"Medford",
			"Milton",
			"Nahant",
			"Natick",
			"New Bedford",
			"Newburyport",
			"Newton",
			"North Adams",
			"Northampton",
			"Norton",
			"Norwood",
			"Peabody",
			"Pittsfield",
			"Plymouth",
			"Provincetown",
			"Quincy",
			"Randolph",
			"Revere",
			"Salem",
			"Sandwich",
			"Saugus",
			"Somerville",
			"South Hadley",
			"Springfield",
			"Stockbridge",
			"Stoughton",
			"Sturbridge",
			"Sudbury",
			"Taunton",
			"Tewksbury",
			"Truro",
			"Watertown",
			"Webster",
			"Wellesley",
			"Wellfleet",
			"West Bridgewater",
			"West Springfield",
			"Westfield",
			"Weymouth",
			"Whitman",
			"Williamstown",
			"Woburn",
			"Woods Hole",
			"Worcester"
		],
		"Michigan": [
			"Adrian",
			"Alma",
			"Ann Arbor",
			"Battle Creek",
			"Bay City",
			"Benton Harbor",
			"Bloomfield Hills",
			"Cadillac",
			"Charlevoix",
			"Cheboygan",
			"Dearborn",
			"Detroit",
			"East Lansing",
			"Eastpointe",
			"Ecorse",
			"Escanaba",
			"Flint",
			"Grand Haven",
			"Grand Rapids",
			"Grayling",
			"Grosse Pointe",
			"Hancock",
			"Highland Park",
			"Holland",
			"Houghton",
			"Interlochen",
			"Iron Mountain",
			"Ironwood",
			"Ishpeming",
			"Jackson",
			"Kalamazoo",
			"Lansing",
			"Livonia",
			"Ludington",
			"Mackinaw City",
			"Manistee",
			"Marquette",
			"Menominee",
			"Midland",
			"Monroe",
			"Mount Clemens",
			"Mount Pleasant",
			"Muskegon",
			"Niles",
			"Petoskey",
			"Pontiac",
			"Port Huron",
			"Royal Oak",
			"Saginaw",
			"Saint Ignace",
			"Saint Joseph",
			"Sault Sainte Marie",
			"Traverse City",
			"Trenton",
			"Warren",
			"Wyandotte",
			"Ypsilanti"
		],
		"Minnesota": [
			"Albert Lea",
			"Alexandria",
			"Austin",
			"Bemidji",
			"Bloomington",
			"Brainerd",
			"Crookston",
			"Duluth",
			"Ely",
			"Eveleth",
			"Faribault",
			"Fergus Falls",
			"Hastings",
			"Hibbing",
			"International Falls",
			"Little Falls",
			"Mankato",
			"Minneapolis",
			"Moorhead",
			"New Ulm",
			"Northfield",
			"Owatonna",
			"Pipestone",
			"Red Wing",
			"Rochester",
			"Saint Cloud",
			"Saint Paul",
			"Sauk Centre",
			"South Saint Paul",
			"Stillwater",
			"Virginia",
			"Willmar",
			"Winona"
		],
		"Mississippi": [
			"Bay Saint Louis",
			"Biloxi",
			"Canton",
			"Clarksdale",
			"Columbia",
			"Columbus",
			"Corinth",
			"Greenville",
			"Greenwood",
			"Grenada",
			"Gulfport",
			"Hattiesburg",
			"Holly Springs",
			"Jackson",
			"Laurel",
			"Meridian",
			"Natchez",
			"Ocean Springs",
			"Oxford",
			"Pascagoula",
			"Pass Christian",
			"Philadelphia",
			"Port Gibson",
			"Starkville",
			"Tupelo",
			"Vicksburg",
			"West Point",
			"Yazoo City"
		],
		"Missouri": [
			"Boonville",
			"Branson",
			"Cape Girardeau",
			"Carthage",
			"Chillicothe",
			"Clayton",
			"Columbia",
			"Excelsior Springs",
			"Ferguson",
			"Florissant",
			"Fulton",
			"Hannibal",
			"Independence",
			"Jefferson City",
			"Joplin",
			"Kansas City",
			"Kirksville",
			"Lamar",
			"Lebanon",
			"Lexington",
			"Maryville",
			"Mexico",
			"Monett",
			"Neosho",
			"New Madrid",
			"Rolla",
			"Saint Charles",
			"Saint Joseph",
			"Saint Louis",
			"Sainte Genevieve",
			"Salem",
			"Sedalia",
			"Springfield",
			"Warrensburg",
			"West Plains"
		],
		"Montana": [
			"Anaconda",
			"Billings",
			"Bozeman",
			"Butte",
			"Dillon",
			"Fort Benton",
			"Glendive",
			"Great Falls",
			"Havre",
			"Helena",
			"Kalispell",
			"Lewistown",
			"Livingston",
			"Miles City",
			"Missoula",
			"Virginia City"
		],
		"Nebraska": [
			"Beatrice",
			"Bellevue",
			"Boys Town",
			"Chadron",
			"Columbus",
			"Fremont",
			"Grand Island",
			"Hastings",
			"Kearney",
			"Lincoln",
			"McCook",
			"Minden",
			"Nebraska City",
			"Norfolk",
			"North Platte",
			"Omaha",
			"Plattsmouth",
			"Red Cloud",
			"Sidney"
		],
		"Nevada": [
			"Boulder City",
			"Carson City",
			"Elko",
			"Ely",
			"Fallon",
			"Genoa",
			"Goldfield",
			"Henderson",
			"Las Vegas",
			"North Las Vegas",
			"Reno",
			"Sparks",
			"Virginia City",
			"Winnemucca"
		],
		"New Hampshire": [
			"Berlin",
			"Claremont",
			"Concord",
			"Derry",
			"Dover",
			"Durham",
			"Exeter",
			"Franklin",
			"Hanover",
			"Hillsborough",
			"Keene",
			"Laconia",
			"Lebanon",
			"Manchester",
			"Nashua",
			"Peterborough",
			"Plymouth",
			"Portsmouth",
			"Rochester",
			"Salem",
			"Somersworth"
		],
		"New Jersey": [
			"Asbury Park",
			"Atlantic City",
			"Bayonne",
			"Bloomfield",
			"Bordentown",
			"Bound Brook",
			"Bridgeton",
			"Burlington",
			"Caldwell",
			"Camden",
			"Cape May",
			"Clifton",
			"Cranford",
			"East Orange",
			"Edison",
			"Elizabeth",
			"Englewood",
			"Fort Lee",
			"Glassboro",
			"Hackensack",
			"Haddonfield",
			"Hoboken",
			"Irvington",
			"Jersey City",
			"Lakehurst",
			"Lakewood",
			"Long Beach",
			"Long Branch",
			"Madison",
			"Menlo Park",
			"Millburn",
			"Millville",
			"Montclair",
			"Morristown",
			"Mount Holly",
			"New Brunswick",
			"New Milford",
			"Newark",
			"Ocean City",
			"Orange",
			"Parsippany–Troy Hills",
			"Passaic",
			"Paterson",
			"Perth Amboy",
			"Plainfield",
			"Princeton",
			"Ridgewood",
			"Roselle",
			"Rutherford",
			"Salem",
			"Somerville",
			"South Orange Village",
			"Totowa",
			"Trenton",
			"Union",
			"Union City",
			"Vineland",
			"Wayne",
			"Weehawken",
			"West New York",
			"West Orange",
			"Willingboro",
			"Woodbridge"
		],
		"New Mexico": [
			"Acoma",
			"Alamogordo",
			"Albuquerque",
			"Artesia",
			"Belen",
			"Carlsbad",
			"Clovis",
			"Deming",
			"Farmington",
			"Gallup",
			"Grants",
			"Hobbs",
			"Las Cruces",
			"Las Vegas",
			"Los Alamos",
			"Lovington",
			"Portales",
			"Raton",
			"Roswell",
			"Santa Fe",
			"Shiprock",
			"Silver City",
			"Socorro",
			"Taos",
			"Truth or Consequences",
			"Tucumcari"
		],
		"New York": [
			"Albany",
			"Amsterdam",
			"Auburn",
			"Babylon",
			"Batavia",
			"Beacon",
			"Bedford",
			"Binghamton",
			"Bronx",
			"Brooklyn",
			"Buffalo",
			"Chautauqua",
			"Cheektowaga",
			"Clinton",
			"Cohoes",
			"Coney Island",
			"Cooperstown",
			"Corning",
			"Cortland",
			"Crown Point",
			"Dunkirk",
			"East Aurora",
			"East Hampton",
			"Eastchester",
			"Elmira",
			"Flushing",
			"Forest Hills",
			"Fredonia",
			"Garden City",
			"Geneva",
			"Glens Falls",
			"Gloversville",
			"Great Neck",
			"Hammondsport",
			"Harlem",
			"Hempstead",
			"Herkimer",
			"Hudson",
			"Huntington",
			"Hyde Park",
			"Ilion",
			"Ithaca",
			"Jamestown",
			"Johnstown",
			"Kingston",
			"Lackawanna",
			"Lake Placid",
			"Levittown",
			"Lockport",
			"Mamaroneck",
			"Manhattan",
			"Massena",
			"Middletown",
			"Mineola",
			"Mount Vernon",
			"New Paltz",
			"New Rochelle",
			"New Windsor",
			"New York City",
			"Newburgh",
			"Niagara Falls",
			"North Hempstead",
			"Nyack",
			"Ogdensburg",
			"Olean",
			"Oneida",
			"Oneonta",
			"Ossining",
			"Oswego",
			"Oyster Bay",
			"Palmyra",
			"Peekskill",
			"Plattsburgh",
			"Port Washington",
			"Potsdam",
			"Poughkeepsie",
			"Queens",
			"Rensselaer",
			"Rochester",
			"Rome",
			"Rotterdam",
			"Rye",
			"Sag Harbor",
			"Saranac Lake",
			"Saratoga Springs",
			"Scarsdale",
			"Schenectady",
			"Seneca Falls",
			"Southampton",
			"Staten Island",
			"Stony Brook",
			"Stony Point",
			"Syracuse",
			"Tarrytown",
			"Ticonderoga",
			"Tonawanda",
			"Troy",
			"Utica",
			"Watertown",
			"Watervliet",
			"Watkins Glen",
			"West Seneca",
			"White Plains",
			"Woodstock",
			"Yonkers"
		],
		"North Carolina": [
			"Asheboro",
			"Asheville",
			"Bath",
			"Beaufort",
			"Boone",
			"Burlington",
			"Chapel Hill",
			"Charlotte",
			"Concord",
			"Durham",
			"Edenton",
			"Elizabeth City",
			"Fayetteville",
			"Gastonia",
			"Goldsboro",
			"Greensboro",
			"Greenville",
			"Halifax",
			"Henderson",
			"Hickory",
			"High Point",
			"Hillsborough",
			"Jacksonville",
			"Kinston",
			"Kitty Hawk",
			"Lumberton",
			"Morehead City",
			"Morganton",
			"Nags Head",
			"New Bern",
			"Pinehurst",
			"Raleigh",
			"Rocky Mount",
			"Salisbury",
			"Shelby",
			"Washington",
			"Wilmington",
			"Wilson",
			"Winston - Salem"
		],
		"North Dakota": [
			"Bismarck",
			"Devils Lake",
			"Dickinson",
			"Fargo",
			"Grand Forks",
			"Jamestown",
			"Mandan",
			"Minot",
			"Rugby",
			"Valley City",
			"Wahpeton",
			"Williston"
		],
		"Ohio": [
			"Akron",
			"Alliance",
			"Ashtabula",
			"Athens",
			"Barberton",
			"Bedford",
			"Bellefontaine",
			"Bowling Green",
			"Canton",
			"Chillicothe",
			"Cincinnati",
			"Cleveland",
			"Cleveland Heights",
			"Columbus",
			"Conneaut",
			"Cuyahoga Falls",
			"Dayton",
			"Defiance",
			"Delaware",
			"East Cleveland",
			"East Liverpool",
			"Elyria",
			"Euclid",
			"Findlay",
			"Gallipolis",
			"Greenville",
			"Hamilton",
			"Kent",
			"Kettering",
			"Lakewood",
			"Lancaster",
			"Lima",
			"Lorain",
			"Mansfield",
			"Marietta",
			"Marion",
			"Martins Ferry",
			"Massillon",
			"Mentor",
			"Middletown",
			"Milan",
			"Mount Vernon",
			"New Philadelphia",
			"Newark",
			"Niles",
			"North College Hill",
			"Norwalk",
			"Oberlin",
			"Painesville",
			"Parma",
			"Piqua",
			"Portsmouth",
			"Put -in -Bay",
			"Salem",
			"Sandusky",
			"Shaker Heights",
			"Springfield",
			"Steubenville",
			"Tiffin",
			"Toledo",
			"Urbana",
			"Warren",
			"Wooster",
			"Worthington",
			"Xenia",
			"Yellow Springs",
			"Youngstown",
			"Zanesville"
		],
		"Oklahoma": [
			"Ada",
			"Altus",
			"Alva",
			"Anadarko",
			"Ardmore",
			"Bartlesville",
			"Bethany",
			"Chickasha",
			"Claremore",
			"Clinton",
			"Cushing",
			"Duncan",
			"Durant",
			"Edmond",
			"El Reno",
			"Elk City",
			"Enid",
			"Eufaula",
			"Frederick",
			"Guthrie",
			"Guymon",
			"Hobart",
			"Holdenville",
			"Hugo",
			"Lawton",
			"McAlester",
			"Miami",
			"Midwest City",
			"Moore",
			"Muskogee",
			"Norman",
			"Oklahoma City",
			"Okmulgee",
			"Pauls Valley",
			"Pawhuska",
			"Perry",
			"Ponca City",
			"Pryor",
			"Sallisaw",
			"Sand Springs",
			"Sapulpa",
			"Seminole",
			"Shawnee",
			"Stillwater",
			"Tahlequah",
			"The Village",
			"Tulsa",
			"Vinita",
			"Wewoka",
			"Woodward"
		],
		"Oregon": [
			"Albany",
			"Ashland",
			"Astoria",
			"Baker City",
			"Beaverton",
			"Bend",
			"Brookings",
			"Burns",
			"Coos Bay",
			"Corvallis",
			"Eugene",
			"Grants Pass",
			"Hillsboro",
			"Hood River",
			"Jacksonville",
			"John Day",
			"Klamath Falls",
			"La Grande",
			"Lake Oswego",
			"Lakeview",
			"McMinnville",
			"Medford",
			"Newberg",
			"Newport",
			"Ontario",
			"Oregon City",
			"Pendleton",
			"Port Orford",
			"Portland",
			"Prineville",
			"Redmond",
			"Reedsport",
			"Roseburg",
			"Salem",
			"Seaside",
			"Springfield",
			"The Dalles",
			"Tillamook"
		],
		"Pennsylvania": [
			"Abington",
			"Aliquippa",
			"Allentown",
			"Altoona",
			"Ambridge",
			"Bedford",
			"Bethlehem",
			"Bloomsburg",
			"Bradford",
			"Bristol",
			"Carbondale",
			"Carlisle",
			"Chambersburg",
			"Chester",
			"Columbia",
			"Easton",
			"Erie",
			"Franklin",
			"Germantown",
			"Gettysburg",
			"Greensburg",
			"Hanover",
			"Harmony",
			"Harrisburg",
			"Hazleton",
			"Hershey",
			"Homestead",
			"Honesdale",
			"Indiana",
			"Jeannette",
			"Jim Thorpe",
			"Johnstown",
			"Lancaster",
			"Lebanon",
			"Levittown",
			"Lewistown",
			"Lock Haven",
			"Lower Southampton",
			"McKeesport",
			"Meadville",
			"Middletown",
			"Monroeville",
			"Nanticoke",
			"New Castle",
			"New Hope",
			"New Kensington",
			"Norristown",
			"Oil City",
			"Philadelphia",
			"Phoenixville",
			"Pittsburgh",
			"Pottstown",
			"Pottsville",
			"Reading",
			"Scranton",
			"Shamokin",
			"Sharon",
			"State College",
			"Stroudsburg",
			"Sunbury",
			"Swarthmore",
			"Tamaqua",
			"Titusville",
			"Uniontown",
			"Warren",
			"Washington",
			"West Chester",
			"Wilkes - Barre",
			"Williamsport",
			"York"
		],
		"Rhode Island": [
			"Barrington",
			"Bristol",
			"Central Falls",
			"Cranston",
			"East Greenwich",
			"East Providence",
			"Kingston",
			"Middletown",
			"Narragansett",
			"Newport",
			"North Kingstown",
			"Pawtucket",
			"Portsmouth",
			"Providence",
			"South Kingstown",
			"Tiverton",
			"Warren",
			"Warwick",
			"Westerly",
			"Wickford",
			"Woonsocket"
		],
		"South Carolina": [
			"Abbeville",
			"Aiken",
			"Anderson",
			"Beaufort",
			"Camden",
			"Charleston",
			"Columbia",
			"Darlington",
			"Florence",
			"Gaffney",
			"Georgetown",
			"Greenville",
			"Greenwood",
			"Hartsville",
			"Lancaster",
			"Mount Pleasant",
			"Myrtle Beach",
			"Orangeburg",
			"Rock Hill",
			"Spartanburg",
			"Sumter",
			"Union"
		],
		"South Dakota": [
			"Aberdeen",
			"Belle Fourche",
			"Brookings",
			"Canton",
			"Custer",
			"De Smet",
			"Deadwood",
			"Hot Springs",
			"Huron",
			"Lead",
			"Madison",
			"Milbank",
			"Mitchell",
			"Mobridge",
			"Pierre",
			"Rapid City",
			"Sioux Falls",
			"Spearfish",
			"Sturgis",
			"Vermillion",
			"Watertown",
			"Yankton"
		],
		"Tennessee": [
			"Alcoa",
			"Athens",
			"Chattanooga",
			"Clarksville",
			"Cleveland",
			"Columbia",
			"Cookeville",
			"Dayton",
			"Elizabethton",
			"Franklin",
			"Gallatin",
			"Gatlinburg",
			"Greeneville",
			"Jackson",
			"Johnson City",
			"Jonesborough",
			"Kingsport",
			"Knoxville",
			"Lebanon",
			"Maryville",
			"Memphis",
			"Morristown",
			"Murfreesboro",
			"Nashville",
			"Norris",
			"Oak Ridge",
			"Shelbyville",
			"Tullahoma"
		],
		"Texas": [
			"Abilene",
			"Alpine",
			"Amarillo",
			"Arlington",
			"Austin",
			"Baytown",
			"Beaumont",
			"Big Spring",
			"Borger",
			"Brownsville",
			"Bryan",
			"Canyon",
			"Cleburne",
			"College Station",
			"Corpus Christi",
			"Crystal City",
			"Dallas",
			"Del Rio",
			"Denison",
			"Denton",
			"Eagle Pass",
			"Edinburg",
			"El Paso",
			"Fort Worth",
			"Freeport",
			"Galveston",
			"Garland",
			"Goliad",
			"Greenville",
			"Harlingen",
			"Houston",
			"Huntsville",
			"Irving",
			"Johnson City",
			"Kilgore",
			"Killeen",
			"Kingsville",
			"Laredo",
			"Longview",
			"Lubbock",
			"Lufkin",
			"Marshall",
			"McAllen",
			"McKinney",
			"Mesquite",
			"Midland",
			"Mission",
			"Nacogdoches",
			"New Braunfels",
			"Odessa",
			"Orange",
			"Pampa",
			"Paris",
			"Pasadena",
			"Pecos",
			"Pharr",
			"Plainview",
			"Plano",
			"Port Arthur",
			"Port Lavaca",
			"Richardson",
			"San Angelo",
			"San Antonio",
			"San Felipe",
			"San Marcos",
			"Sherman",
			"Sweetwater",
			"Temple",
			"Texarkana",
			"Texas City",
			"Tyler",
			"Uvalde",
			"Victoria",
			"Waco",
			"Weatherford",
			"Wichita Falls",
			"Ysleta"
		],
		"Utah": [
			"Alta",
			"American Fork",
			"Bountiful",
			"Brigham City",
			"Cedar City",
			"Clearfield",
			"Delta",
			"Fillmore",
			"Green River",
			"Heber City",
			"Kanab",
			"Layton",
			"Lehi",
			"Logan",
			"Manti",
			"Moab",
			"Monticello",
			"Murray",
			"Nephi",
			"Ogden",
			"Orderville",
			"Orem",
			"Panguitch",
			"Park City",
			"Payson",
			"Price",
			"Provo",
			"Saint George",
			"Salt Lake City",
			"Spanish Fork",
			"Springville",
			"Tooele",
			"Vernal"
		],
		"Vermont": [
			"Barre",
			"Bellows Falls",
			"Bennington",
			"Brattleboro",
			"Burlington",
			"Essex",
			"Manchester",
			"Middlebury",
			"Montpelier",
			"Newport",
			"Plymouth",
			"Rutland",
			"Saint Albans",
			"Saint Johnsbury",
			"Sharon",
			"Winooski"
		],
		"Virginia": [
			"Abingdon",
			"Alexandria",
			"Bristol",
			"Charlottesville",
			"Chesapeake",
			"Danville",
			"Fairfax",
			"Falls Church",
			"Fredericksburg",
			"Hampton",
			"Hanover",
			"Hopewell",
			"Lexington",
			"Lynchburg",
			"Manassas",
			"Martinsville",
			"New Market",
			"Newport News",
			"Norfolk",
			"Petersburg",
			"Portsmouth",
			"Reston",
			"Richmond",
			"Roanoke",
			"Staunton",
			"Suffolk",
			"Virginia Beach",
			"Waynesboro",
			"Williamsburg",
			"Winchester"
		],
		"Washington": [
			"Aberdeen",
			"Anacortes",
			"Auburn",
			"Bellevue",
			"Bellingham",
			"Bremerton",
			"Centralia",
			"Coulee Dam",
			"Coupeville",
			"Ellensburg",
			"Ephrata",
			"Everett",
			"Hoquiam",
			"Kelso",
			"Kennewick",
			"Longview",
			"Moses Lake",
			"Oak Harbor",
			"Olympia",
			"Pasco",
			"Point Roberts",
			"Port Angeles",
			"Pullman",
			"Puyallup",
			"Redmond",
			"Renton",
			"Richland",
			"Seattle",
			"Spokane",
			"Tacoma",
			"Vancouver",
			"Walla Walla",
			"Wenatchee",
			"Yakima"
		],
		"West Virginia": [
			"Bath",
			"Beckley",
			"Bluefield",
			"Buckhannon",
			"Charles Town",
			"Charleston",
			"Clarksburg",
			"Elkins",
			"Fairmont",
			"Grafton",
			"Harpers Ferry",
			"Hillsboro",
			"Hinton",
			"Huntington",
			"Keyser",
			"Lewisburg",
			"Logan",
			"Martinsburg",
			"Morgantown",
			"Moundsville",
			"New Martinsville",
			"Parkersburg",
			"Philippi",
			"Point Pleasant",
			"Princeton",
			"Romney",
			"Shepherdstown",
			"South Charleston",
			"Summersville",
			"Weirton",
			"Welch",
			"Wellsburg",
			"Weston",
			"Wheeling",
			"White Sulphur Springs",
			"Williamson"
		],
		"Wisconsin": [
			"Appleton",
			"Ashland",
			"Baraboo",
			"Belmont",
			"Beloit",
			"Eau Claire",
			"Fond du Lac",
			"Green Bay",
			"Hayward",
			"Janesville",
			"Kenosha",
			"La Crosse",
			"Lake Geneva",
			"Madison",
			"Manitowoc",
			"Marinette",
			"Menasha",
			"Milwaukee",
			"Neenah",
			"New Glarus",
			"Oconto",
			"Oshkosh",
			"Peshtigo",
			"Portage",
			"Prairie du Chien",
			"Racine",
			"Rhinelander",
			"Ripon",
			"Sheboygan",
			"Spring Green",
			"Stevens Point",
			"Sturgeon Bay",
			"Superior",
			"Waukesha",
			"Wausau",
			"Wauwatosa",
			"West Allis",
			"West Bend",
			"Wisconsin Dells"
		],
		"Wyoming": [
			"Buffalo",
			"Casper",
			"Cheyenne",
			"Cody",
			"Douglas",
			"Evanston",
			"Gillette",
			"Green River",
			"Jackson",
			"Lander",
			"Laramie",
			"Newcastle",
			"Powell",
			"Rawlins",
			"Riverton",
			"Rock Springs",
			"Sheridan",
			"Ten Sleep",
			"Thermopolis",
			"Torrington",
			"Worland"
		]
	}
}